version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops123
      POSTGRES_DB: devopsdb
      POSTGRES_HOST: db
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: devops
      POSTGRES_PASSWORD: devops123
      POSTGRES_DB: devopsdb
    ports:
      - "5432:5432"

